config/urls.py
"""This contains all of the base URL mappings used by Ghostwriter."""

# Django Imports
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path, re_path
from django.views import defaults as default_views
from django.views.generic import RedirectView

# Ghostwriter Libraries
from ghostwriter.home.views import protected_serve
from ghostwriter.users.views import (
    account_change_password,
    account_reset_password_from_key,
)

urlpatterns = [
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("ghostwriter.users.urls", namespace="users")),
    path("home/", include("ghostwriter.home.urls", namespace="home")),
    path(
        "accounts/password/change/",
        account_change_password,
        name="account_change_password",
    ),
    re_path(
        r"^accounts/password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
        account_reset_password_from_key,
        name="account_reset_password_from_key",
    ),
    path("accounts/", include("allauth.urls")),
    # path("accounts/", include("django.contrib.auth.urls")),
    path("rolodex/", include("ghostwriter.rolodex.urls", namespace="rolodex")),
    path("shepherd/", include("ghostwriter.shepherd.urls", namespace="shepherd")),
    path("reporting/", include("ghostwriter.reporting.urls", namespace="reporting")),
    path("", RedirectView.as_view(pattern_name="home:dashboard"), name="home"),
    path("oplog/", include("ghostwriter.oplog.urls", namespace="oplog")),
    re_path(
        r"^%s(?P<path>.*)$" % settings.MEDIA_URL[1:],
        protected_serve,
        {"document_root": settings.MEDIA_ROOT},
    ),
    path("api/", include("ghostwriter.api.urls", namespace="api")),
    path("status/", include("ghostwriter.status.urls", namespace="status")),
    # Add additional custom paths below this line...
    # Your stuff: custom urls includes go here
]

if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:

        import debug_toolbar  # noqa isort:skip

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

ghostwriter/oplog/urls.py
"""This contains all of the URL mappings used by the Oplog application."""


# Django Imports
from django.urls import include, path

# 3rd Party Libraries
from rest_framework import routers

from . import views

app_name = "ghostwriter.oplog"

router = routers.DefaultRouter()
router.register("entries", views.OplogEntryViewSet)
router.register("oplogs", views.OplogViewSet)

urlpatterns = [
    path("", views.index, name="index"),
    path("api/", include(router.urls)),
    path("create/<int:pk>", views.OplogCreate.as_view(), name="oplog_create"),
    path("create/", views.OplogCreate.as_view(), name="oplog_create_no_project"),
    path(
        "<int:pk>/entries/create",
        views.OplogEntryCreate.as_view(),
        name="oplog_entry_create",
    ),
    path(
        "<int:pk>/entries/update",
        views.OplogEntryUpdate.as_view(),
        name="oplog_entry_update",
    ),
    path(
        "<int:pk>/entries/delete",
        views.OplogEntryDelete.as_view(),
        name="oplog_entry_delete",
    ),
    path("<int:pk>/entries", views.OplogListEntries, name="oplog_entries"),
    path("import", views.OplogEntriesImport, name="oplog_import"),
]

# URLs for AJAX requests
urlpatterns += [
    path("ajax/oplog/mute/<int:pk>", views.OplogMuteToggle.as_view(), name="ajax_oplog_mute_toggle"),
]

ghostwriter/rolodex/urls.py
"""This contains all of the URL mappings used by the Rolodex application."""

# Django Imports
from django.urls import path

from . import views

app_name = "rolodex"

# URLs for the basic views
urlpatterns = [
    path("", views.index, name="index"),
    path("clients/", views.client_list, name="clients"),
    path("projects/", views.project_list, name="projects"),
]

# URLs for AJAX requests – deletion and toggle views
urlpatterns += [
    path(
        "ajax/codename/roll",
        views.roll_codename,
        name="ajax_roll_codename",
    ),
    path(
        "ajax/project/toggle/<int:pk>",
        views.ProjectStatusToggle.as_view(),
        name="ajax_toggle_project",
    ),
    path(
        "ajax/project/objective/status/<int:pk>",
        views.ProjectObjectiveStatusUpdate.as_view(),
        name="ajax_set_objective_status",
    ),
    path(
        "ajax/project/objective/order",
        views.ajax_update_project_objectives,
        name="ajax_update_objective_order",
    ),
    path(
        "ajax/project/objective/toggle/<int:pk>",
        views.ProjectObjectiveToggle.as_view(),
        name="ajax_toggle_project_objective",
    ),
    path(
        "ajax/project/objective/refresh/<int:pk>",
        views.ProjectObjectiveRefresh.as_view(),
        name="ajax_update_objective_row",
    ),
    path(
        "ajax/project/objective/delete/<int:pk>",
        views.ProjectObjectiveDelete.as_view(),
        name="ajax_delete_project_objective",
    ),
    path(
        "ajax/project/deconfliction/delete/<int:pk>",
        views.DeconflictionDelete.as_view(),
        name="ajax_delete_project_deconfliction",
    ),
    path(
        "ajax/project/assignment/delete/<int:pk>",
        views.ProjectAssignmentDelete.as_view(),
        name="ajax_delete_project_assignment",
    ),
    path(
        "ajax/project/note/delete/<int:pk>",
        views.ProjectNoteDelete.as_view(),
        name="ajax_delete_project_note",
    ),
    path(
        "ajax/client/contact/delete/<int:pk>",
        views.ClientContactDelete.as_view(),
        name="ajax_delete_client_poc",
    ),
    path(
        "ajax/client/note/delete/<int:pk>",
        views.ClientNoteDelete.as_view(),
        name="ajax_delete_client_note",
    ),
    path(
        "ajax/project/refresh/<int:pk>",
        views.update_project_badges,
        name="ajax_update_project_badges",
    ),
    path(
        "ajax/client/refresh/<int:pk>",
        views.update_client_badges,
        name="ajax_update_client_badges",
    ),
    path(
        "ajax/project/target/compromise/<int:pk>",
        views.ProjectTargetToggle.as_view(),
        name="ajax_toggle_project_target",
    ),
    path(
        "ajax/project/target/delete/<int:pk>",
        views.ProjectTargetDelete.as_view(),
        name="ajax_delete_project_target",
    ),
    path(
        "ajax/project/scope/delete/<int:pk>",
        views.ProjectScopeDelete.as_view(),
        name="ajax_delete_project_scope",
    ),
    path(
        "ajax/project/scope/export/<int:pk>",
        views.ProjectScopeExport.as_view(),
        name="ajax_export_project_scope",
    ),
    path(
        "ajax/project/task/create/<int:pk>",
        views.ProjectTaskCreate.as_view(),
        name="ajax_create_project_task",
    ),
    path(
        "ajax/project/task/toggle/<int:pk>",
        views.ProjectTaskToggle.as_view(),
        name="ajax_toggle_project_task",
    ),
    path(
        "ajax/project/task/delete/<int:pk>",
        views.ProjectTaskDelete.as_view(),
        name="ajax_delete_project_task",
    ),
    path(
        "ajax/project/task/update/<int:pk>",
        views.ProjectTaskUpdate.as_view(),
        name="ajax_update_project_task",
    ),
    path(
        "ajax/project/task/refresh/<int:pk>",
        views.ProjectTaskRefresh.as_view(),
        name="ajax_update_objective_tasks",
    ),
]

# URLs for :model:`Client` Class Based Views
urlpatterns += [
    path("clients/<int:pk>", views.ClientDetailView.as_view(), name="client_detail"),
    path("clients/create/", views.ClientCreate.as_view(), name="client_create"),
    path("clients/update/<int:pk>", views.ClientUpdate.as_view(), name="client_update"),
    path("clients/delete/<int:pk>", views.ClientDelete.as_view(), name="client_delete"),
    path(
        "clients/notes/create/<int:pk>",
        views.ClientNoteCreate.as_view(),
        name="client_note_add",
    ),
    path(
        "clients/notes/update/<int:pk>",
        views.ClientNoteUpdate.as_view(),
        name="client_note_edit",
    ),
]

# URLs for :model:`Project` Class Based Views
urlpatterns += [
    path("projects/<int:pk>", views.ProjectDetailView.as_view(), name="project_detail"),
    path(
        "projects/create",
        views.ProjectCreate.as_view(),
        name="project_create_no_client",
    ),
    path(
        "projects/create/<int:pk>", views.ProjectCreate.as_view(), name="project_create"
    ),
    path(
        "projects/update/<int:pk>",
        views.ProjectUpdate.as_view(),
        name="project_update",
    ),
    path(
        "projects/delete/<int:pk>",
        views.ProjectDelete.as_view(),
        name="project_delete",
    ),
    path(
        "projects/notes/create/<int:pk>",
        views.ProjectNoteCreate.as_view(),
        name="project_note_add",
    ),
    path(
        "projects/notes/update/<int:pk>",
        views.ProjectNoteUpdate.as_view(),
        name="project_note_edit",
    ),
    path(
        "projects/deconfliction/create/<int:pk>",
        views.DeconflictionCreate.as_view(),
        name="project_deconfliction_create",
    ),
    path(
        "projects/deconfliction/update/<int:pk>",
        views.DeconflictionUpdate.as_view(),
        name="project_deconfliction_update",
    ),
]

ghostwriter/oplog/forms.py
"""This contains all of the forms used by the Oplog application."""


# Django Imports
from django import forms

# 3rd Party Libraries
from crispy_forms.helper import FormHelper
from crispy_forms.layout import HTML, ButtonHolder, Layout, Submit

# Ghostwriter Libraries
from ghostwriter.rolodex.models import Project

from .models import Oplog, OplogEntry


class OplogForm(forms.ModelForm):
    """
    Save an individual :model:`oplog.Oplog`.
    """

    class Meta:
        model = Oplog
        fields = "__all__"

    def __init__(self, project=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.project_instance = project
        # Limit the list to just projects not marked as complete
        active_projects = Project.objects.filter(complete=False).order_by("-start_date")
        if active_projects:
            self.fields["project"].empty_label = "-- Select an Active Project --"
        else:
            self.fields["project"].empty_label = "-- No Active Projects --"
        self.fields["project"].queryset = active_projects
        for field in self.fields:
            self.fields[field].widget.attrs["autocomplete"] = "off"
        # Design form layout with Crispy FormHelper
        self.helper = FormHelper()
        self.helper.form_show_errors = False
        self.helper.form_show_labels = True
        self.helper.form_method = "post"
        self.helper.form_class = "newitem"
        self.helper.layout = Layout(
            "name",
            "project",
            ButtonHolder(
                Submit("submit_btn", "Submit", css_class="btn btn-primary col-md-4"),
                HTML(
                    """
                    <button onclick="window.location.href='{{ cancel_link }}'" class="btn btn-outline-secondary col-md-4" type="button">Cancel</button>
                    """
                ),
            ),
        )


class OplogEntryForm(forms.ModelForm):
    """
    Save an individual :model:`oplog.OplogEntry`.
    """

    class Meta:
        model = OplogEntry
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.oplog_id = pk
        for field in self.fields:
            self.fields[field].widget.attrs["autocomplete"] = "off"
        self.helper = FormHelper()
        self.helper.form_class = "form-inline"
        self.helper.form_method = "post"
        self.helper.field_class = "h-100 justify-content-center align-items-center"

ghostwriter/oplog/templates/oplog/oplog_form.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}

{% block pagetitle %}Oplog Creation{% endblock %}

{% block breadcrumbs %}
    <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'home:dashboard' %}">Dashboard</a></li>
            {% comment %} Check if `project` is in the context to determine if this is a new lgo for a specific project and adjust breadcrumbs accordingly {% endcomment %}
            {% if project %}
                <li class="breadcrumb-item"><a data-toggle="tooltip" title="{{ project.client }}" href="{% url 'rolodex:client_detail' project.client.id %}">{{ project.client }}</a></li>
                <li class="breadcrumb-item"><a data-toggle="tooltip" title="{{ project }}" href="{% url 'rolodex:project_detail' project.id %}">{{ project.start_date|date:"DATE_FORMAT" }} {{ project.project_type }}</a></li>
            {% else %}
                <li class="breadcrumb-item"><a href="{% url 'oplog:index' %}">Operation Logs</a></li>
            {% endif %}
            <li class="breadcrumb-item active" aria-current="page">New Log Form</li>
        </ul>
    </nav>
{% endblock %}

{% block content %}
    <!-- Instructions Section -->
    <p>Provide a meaningful name for your log and select the project to which it should associated:</p>

    <!-- Form Error Section -->
    {% if form.errors %}
        <script>
            {% for field in form %}
                {% for error in field.errors %}
                    displayToastTop({type:'error', string:'{{ error }}', context:'form'});
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                displayToastTop({type:'error', string:'{{ error }}', context:'form'});
            {% endfor %}
        </script>
    {% endif %}

    <!-- Form Section -->
    {% crispy form form.helper %}
{% endblock %}

ghostwriter/oplog/templates/oplog/oplog_import.html
{% extends "base_generic.html" %}

{% block pagetitle %}Domain Entry{% endblock %}

{% block breadcrumbs %}
    <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'home:dashboard' %}">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="{% url 'oplog:index' %}">Operation Logs</a></li>
            <li class="breadcrumb-item active" aria-current="page">Log Import</li>
        </ul>
    </nav>
{% endblock %}

{% block content %}
<!-- File Upload -->
<h2>Upload Operation Log Entries CSV</h2>
<p>Upload a csv file containing log entries to be imported:</p>
<form action="{% url 'oplog:oplog_import'%}" method="POST" enctype="multipart/form-data" class="form-horizontal">
    {% csrf_token %}
    <div class="form-group">
        <label for="csv_file" class="csvlabel">
            <div class="csvdiv">Click or drop your csv file here</div>
            <input type="file" id="csv_file" name="csv_file" required="True" accept="text/csv">
        </label>
        <p id="filename"></p>
    </div>
    <div class="form-group">
        <div style="text-align: center"></div>
        <button class="button"><i class="fas fa-file-upload"></i> Upload</button>
    </div>
    </div>
</form>

<!-- Spacer -->
<p style="margin: 40p;"></p>

<!-- Section for Instructions -->
<h3>Instructions</h3>
<div>
    <div class="row">
        <div class="alert alert-success offset-md-2 col-md-8 mt-1" role="alert">
            <h4 class="alert-heading">CSV Headers</h4>
            <p>Your csv file must have these headers:</p>
            <em>
                oplog_id, start_date, end_date, source_ip, dest_ip, tool, user_context, command, description, output,
                comments, operator_name
            </em>
        </div>
    </div>

    <div class="row">
        <div class="alert alert-warning offset-md-2 col-md-8 mt-2" role="alert">
            <h4 class="alert-heading">Note on Timestamps</h4>
            <p>Your <em>start_date</em> and <em>end_date</em> values must be in the <em>YYYY-MM-DD HH:MM:SS</em> format.</p>
        </div>
    </div>
</div>
{% endblock %}

{% block morescripts %}
<!-- Script for Upload Form -->
<script>
    $('input[type=file]').on('change', function () {
        $("#filename").text($(this).val());
    });

    $('input[type=file]').on('dragenter', function () {
        $('csvdiv').addClass('dragover');
    });

    $('input[type=file]').on('dragleave', function () {
        $('csvdiv').removeClass('dragover');
    });
</script>
{% endblock %}

ghostwriter/oplog/templates/oplog/oplog_list.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}
{% load bleach_tags %}

{% block pagetitle %}Operation Logs{% endblock %}

{% block breadcrumbs %}
    <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'home:dashboard' %}">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">Operation Logs</li>
        </ul>
    </nav>
{% endblock %}

{% block content %}
    {% comment %} Conditional display of API key for newly created oplogs {% endcomment %}
    {% for message in messages %}
        {% if "api-key" in message.tags %}
            <div class="alert alert-success" role="alert">
                <h4 style="margin-top: 0;" class="alert-heading">Hey You!</h4>
                {{ message|linebreaks }}
            </div>
        {% endif %}
    {% endfor %}

    <!-- Oplog Table Section -->
    <p>
        <a class="icon add-icon" href="{% url 'oplog:oplog_create_no_project' %}">Start New Operation Log</a>
        <span style="padding-right: 20px; padding-left: 20px;">OR</span>
        <a class="icon upload-icon" href="{% url 'oplog:oplog_import' %}">Import Oplog</a>
    </p>
    {% if op_logs %}
        <table id="oplogTable" class="tablesorter table table-hover table-striped table-sm">
            <thead>
                <tr>
                    <th class="align-middle">ID</th>
                    <th class="align-middle">Name</th>
                    <th class="align-middle">Project</th>
                    <th class="align-middle">
                        <div class="dropdown dropleft">
                            <span id="notification-info-btn" class="dropdown-info mr-2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Notifications</span>
                                <div id="notification-info" class="dropdown-menu dropdown-info-content" aria-labelledby="notification-info-btn">
                                <p>Notification status determines if Ghostwriter will send notifications for the log when the "Review Active Logs" task is run.</p>
                            </div>
                        </div>
                    </th>
                    <th class="sorter-false align-middle">Export CSV</th>
                </tr>
            </thead>
            {% for log in op_logs %}
                <tr>
                    <td class="align-middle">{{ log.id }}</td>
                    <td class="align-middle"><a class="clickable" href="{% url 'oplog:oplog_entries' log.pk %}">{{ log.name }}</a></td>
                    <td class="align-middle">{{ log.project.client }} {{ log.project.project_type }} ({{ log.project.start_date }})</td>
                    <td class="align-middle pr-3">
                        {% if log.mute_notifications %}
                            <span class="icon silenced-notification-icon">Silenced</span>
                        {% else %}
                            <span class="icon notification-bell-icon">Active</span>
                        {% endif %}
                    </td>
                    <td class="align-middle js-export-oplog" oplog-id="{{ log.pk }}" oplog-name="{{ log.name }}"><a href="javascript:void(0);" class="btn btn-secondary col-md-12">Export</a></td>
                </tr>
            {% endfor %}
        </table>
    {% else %}
        <p class="mt-3">There are no logs to see here yet. Start or import a log up above.</p>
    {% endif %}
{% endblock %}

{% block morescripts %}
    <!-- jQuery Tablesorter Script -->
    <script>
        $(document).ready(function () {
            $("#oplogTable").tablesorter(
                {
                    cssAsc: ' down', cssDesc: 'up', cssNone: 'none',
                }); $('.tablesorter').trigger('update');
        });
    </script>

    <!-- Export Oplog with JS -->
    <script>
        function download(url, filename) {
            fetch(url).then(function (t) {
                return t.blob().then((b) => {
                    var a = document.createElement("a");
                    a.href = URL.createObjectURL(b);
                    a.setAttribute("download", filename);
                    a.click();
                });
            });
        }

        $(".js-export-oplog").on("click", function () {
            id = $(this).attr('oplog-id')
            name = $(this).attr('oplog-name')
            base_name = `${name}-log-export-${id}.csv`
            filename = generateDownloadName(base_name);
            download(`/oplog/api/entries?export=csv&&oplog_id=${id}`, filename);
        });
    </script>
{% endblock %}

ghostwriter/oplog/templates/oplog/oplogentry_form.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}

{% block pagetitle %}Operation Log Entry{% endblock %}

{% block content %}
<p>Enter log details:</p>

<!-- Form Section -->
<form class="newitem" action="" method="post">
    {% csrf_token %}

    <!-- General Section -->
    <strong><i class="fas fa-database"></i> Operation Log Entry Details</strong>
    <hr>
    {{ form.oplog_id|as_crispy_field }}
    {{ form.start_date|as_crispy_field }}
    {{ form.end_date|as_crispy_field }}
    {{ form.source_ip|as_crispy_field }}
    {{ form.dest_ip|as_crispy_field }}
    {{ form.tool|as_crispy_field }}
    {{ form.user_context|as_crispy_field }}
    {{ form.command|as_crispy_field }}
    {{ form.description|as_crispy_field }}
    {{ form.output|as_crispy_field }}
    {{ form.comments|as_crispy_field }}
    {{ form.operator_name|as_crispy_field }}

    <input type="submit" class="btn btn-primary" value="Save">
    <button onclick="window.history.back();" class="btn btn-secondary" type="button">Cancel</button>
</form>
{% endblock %}