config/urls.py
"""This contains all of the base URL mappings used by Ghostwriter."""

# Django Imports
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path, re_path
from django.views import defaults as default_views
from django.views.generic import RedirectView

# Ghostwriter Libraries
from ghostwriter.home.views import protected_serve
from ghostwriter.users.views import (
    account_change_password,
    account_reset_password_from_key,
)

urlpatterns = [
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("ghostwriter.users.urls", namespace="users")),
    path("home/", include("ghostwriter.home.urls", namespace="home")),
    path(
        "accounts/password/change/",
        account_change_password,
        name="account_change_password",
    ),
    re_path(
        r"^accounts/password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
        account_reset_password_from_key,
        name="account_reset_password_from_key",
    ),
    path("accounts/", include("allauth.urls")),
    # path("accounts/", include("django.contrib.auth.urls")),
    path("rolodex/", include("ghostwriter.rolodex.urls", namespace="rolodex")),
    path("shepherd/", include("ghostwriter.shepherd.urls", namespace="shepherd")),
    path("reporting/", include("ghostwriter.reporting.urls", namespace="reporting")),
    path("", RedirectView.as_view(pattern_name="home:dashboard"), name="home"),
    path("oplog/", include("ghostwriter.oplog.urls", namespace="oplog")),
    re_path(
        r"^%s(?P<path>.*)$" % settings.MEDIA_URL[1:],
        protected_serve,
        {"document_root": settings.MEDIA_ROOT},
    ),
    path("api/", include("ghostwriter.api.urls", namespace="api")),
    path("status/", include("ghostwriter.status.urls", namespace="status")),
    # Add additional custom paths below this line...
    # Your stuff: custom urls includes go here
]

if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:

        import debug_toolbar  # noqa isort:skip

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

ghostwriter/api/urls.py
"""This contains all of the URL mappings used by the API application."""

# Django Imports
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

# Ghostwriter Libraries
from ghostwriter.api.views import (
    ApiKeyCreate,
    ApiKeyRevoke,
    GraphqlAttachFinding,
    GraphqlAuthenticationWebhook,
    GraphqlCheckoutDomain,
    GraphqlCheckoutServer,
    GraphqlDeleteEvidenceAction,
    GraphqlDeleteReportTemplateAction,
    GraphqlDomainCheckoutDelete,
    GraphqlDomainUpdateEvent,
    GraphqlEventTestView,
    GraphqlGenerateReport,
    GraphqlLoginAction,
    GraphqlOplogEntryCreateEvent,
    GraphqlOplogEntryDeleteEvent,
    GraphqlOplogEntryUpdateEvent,
    GraphqlServerCheckoutDelete,
    GraphqlTestView,
    GraphqlWhoami,
)

app_name = "api"

urlpatterns = [
    # Actions
    path("test", csrf_exempt(GraphqlTestView.as_view()), name="graphql_test"),
    path("test_event", csrf_exempt(GraphqlEventTestView.as_view()), name="graphql_event_test"),
    path("webhook", csrf_exempt(GraphqlAuthenticationWebhook.as_view()), name="graphql_webhook"),
    path("login", csrf_exempt(GraphqlLoginAction.as_view()), name="graphql_login"),
    path("whoami", csrf_exempt(GraphqlWhoami.as_view()), name="graphql_whoami"),
    path("whoami", csrf_exempt(GraphqlWhoami.as_view()), name="graphql_whoami"),
    path("generateReport", csrf_exempt(GraphqlGenerateReport.as_view()), name="graphql_generate_report"),
    path("checkoutDomain", csrf_exempt(GraphqlCheckoutDomain.as_view()), name="graphql_checkout_domain"),
    path("checkoutServer", csrf_exempt(GraphqlCheckoutServer.as_view()), name="graphql_checkout_server"),
    path("deleteDomainCheckout", csrf_exempt(GraphqlDomainCheckoutDelete.as_view()), name="graphql_domain_checkout_delete"),
    path("deleteServerCheckout", csrf_exempt(GraphqlServerCheckoutDelete.as_view()), name="graphql_server_checkout_delete"),
    path("deleteEvidence", csrf_exempt(GraphqlDeleteEvidenceAction.as_view()), name="graphql_delete_evidence"),
    path("deleteTemplate", csrf_exempt(GraphqlDeleteReportTemplateAction.as_view()), name="graphql_delete_template"),
    path("attachFinding", csrf_exempt(GraphqlAttachFinding.as_view()), name="graphql_attach_finding"),
    # Events
    path("event/domain/update", csrf_exempt(GraphqlDomainUpdateEvent.as_view()), name="graphql_domain_update_event"),
    path("event/oplogentry/create", csrf_exempt(GraphqlOplogEntryCreateEvent.as_view()), name="graphql_oplogentry_create_event"),
    path("event/oplogentry/update", csrf_exempt(GraphqlOplogEntryUpdateEvent.as_view()), name="graphql_oplogentry_update_event"),
    path("event/oplogentry/delete", csrf_exempt(GraphqlOplogEntryDeleteEvent.as_view()), name="graphql_oplogentry_delete_event"),
    path("ajax/token/revoke/<int:pk>", ApiKeyRevoke.as_view(), name="ajax_revoke_token"),
    path("token/create", ApiKeyCreate.as_view(), name="ajax_create_token"),
]

ghostwriter/users/urls.py
"""This contains all of the URL mappings used by the Users application."""

# Django Imports
from django.urls import path

# Ghostwriter Libraries
from ghostwriter.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
    userprofile_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path(
        "<str:username>/", user_detail_view, name="user_detail"
    ),
    path(
        "<str:username>/update/", user_update_view, name="user_update"
    ),
    path("<str:username>/update/avatar/", view=userprofile_update_view, name="userprofile_update"),
]

ghostwriter/api/models.py
"""This contains all of the database models used by the GraphQL application."""

# Standard Libraries
import typing

# Django Imports
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone

# Ghostwriter Libraries
from ghostwriter.api.utils import generate_jwt, jwt_decode_no_verification

User = get_user_model()


class BaseAPIKeyManager(models.Manager):
    """
    Baseline API key manager used for ``APIKeyManager``.

    Code is adapted from the ``djangorestframework-api-key`` package by florimondmanca.
    """
    def generate_token(self, obj: "AbstractAPIKey") -> str:
        # Generate JWT with requested expiration date instead of default of +15m
        payload, token = generate_jwt(obj.user, exp=obj.expiry_date)
        obj.token = token
        return payload, token

    def create_token(self, **kwargs: typing.Any) -> typing.Tuple["AbstractAPIKey", str]:
        # Prevent from manually setting the primary key.
        kwargs.pop("id", None)
        obj = self.model(**kwargs)
        _, token = self.generate_token(obj)
        obj.save()
        return obj, token

    def get_usable_keys(self) -> models.QuerySet:
        return self.filter(revoked=False)

    def get_from_token(self, token: str) -> "AbstractAPIKey":
        queryset = self.get_usable_keys()

        try:
            entry = queryset.get(token=token)
        except self.model.DoesNotExist:
            raise

        if not entry.is_valid(token):
            raise self.model.DoesNotExist("Key is not valid")
        else:
            return entry

    def is_valid(self, token: str) -> bool:
        try:
            entry = self.get_from_token(token)
        except self.model.DoesNotExist:
            return False

        if entry.has_expired:
            return False

        if not entry.user.is_active:
            return False

        return True


class APIKeyManager(BaseAPIKeyManager):
    pass


class AbstractAPIKey(models.Model):
    """
    Stores a specialized JSON Web Token associated with an individual :model:`users.User`.
    """
    objects = APIKeyManager()

    name = models.CharField(
        max_length=255,
        blank=False,
        default=None,
        help_text=("A name to identify this API key"),
    )
    token = models.TextField(editable=False)
    created = models.DateTimeField(auto_now_add=True, db_index=True)
    expiry_date = models.DateTimeField(
        blank=True,
        null=True,
        verbose_name="Expires",
        help_text="Once API key expires, clients cannot use it anymore",
    )
    revoked = models.BooleanField(
        blank=True,
        default=False,
        help_text=(
            "If the API key is revoked, clients cannot use it anymore (this is irreversible)"
        ),
    )
    # Foreign Keys
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        abstract = True
        ordering = ("-created",)
        verbose_name = "API key"
        verbose_name_plural = "API keys"

    def __init__(self, *args: typing.Any, **kwargs: typing.Any):
        super().__init__(*args, **kwargs)
        # Store the initial value of ``revoked`` to detect changes.
        self._initial_revoked = self.revoked

    def _has_expired(self) -> bool:
        if self.expiry_date is None:
            return False
        return self.expiry_date < timezone.now()

    _has_expired.short_description = "Has expired"
    _has_expired.boolean = True
    has_expired = property(_has_expired)

    def is_valid(self, key: str) -> bool:
        payload = jwt_decode_no_verification(key)
        if payload:
            return True
        return False

    def clean(self) -> None:
        self._validate_revoked()

    def save(self, *args: typing.Any, **kwargs: typing.Any) -> None:
        self._validate_revoked()
        super().save(*args, **kwargs)

    def _validate_revoked(self) -> None:
        if self._initial_revoked and not self.revoked:
            raise ValidationError(
                "The API key has been revoked, which cannot be undone",
                code="revoked",
            )

    def __str__(self) -> str:
        return str(self.name)


class APIKey(AbstractAPIKey):
    """
    Stores a specialized JSON Web Token associated with an individual :model:`users.User`.
    """

ghostwriter/users/views.py
"""This contains all of the views used by the Users application."""

# Django Imports
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse, reverse_lazy
from django.views.generic import DetailView, RedirectView, UpdateView

# 3rd Party Libraries
from allauth.account.views import PasswordChangeView, PasswordResetFromKeyView

# Ghostwriter Libraries
from ghostwriter.home.forms import UserProfileForm
from ghostwriter.home.models import UserProfile
from ghostwriter.users.forms import UserChangeForm

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    """
    Display an individual :model:`users.User`.

    **Template**

    :template:`users/profile.html`
    """

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"
    template_name = "users/profile.html"

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        return ctx

    def get_object(self):
        return get_object_or_404(User, username=self.kwargs.get("username"))

    def get_slug_field(self):  # pragma: no cover``
        return "user__username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """
    Update details for an individual :model:`users.User`.

    **Context**

    ``form``
        A single ``UserChangeForm`` form.
    ``cancel_link``
        Link for the form's Cancel button to return to user's profile page

    **Template**

    :template:`users/profile_form.html`
    """
    model = User
    form_class = UserChangeForm
    template_name = "users/profile_form.html"

    def test_func(self):
        self.object = self.get_object()
        return self.request.user.id == self.object.id

    def handle_no_permission(self):
        if self.request.user.username:
            messages.warning(self.request, "You do not have permission to access that")
            return redirect("users:redirect")
        return redirect("home:dashboard")

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx["cancel_link"] = reverse("users:user_detail", kwargs={"username": self.request.user.username})
        return ctx

    def get_object(self):
        return get_object_or_404(User, username=self.kwargs.get("username"))

    def get_success_url(self):
        messages.success(
            self.request,
            "Successfully updated your profile",
            extra_tags="alert-success",
        )
        return reverse("users:user_detail", kwargs={"username": self.request.user.username})


user_update_view = UserUpdateView.as_view()


class UserProfileUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """
    Update a :model:`home.UserProfile` for an individual :model:`users.User`.

    **Context**

    ``form``
        A single ``UserProfileForm`` form.
    ``cancel_link``
        Link for the form's Cancel button to return to user's profile page

    **Template**

    :template:`users/profile_form.html`
    """

    model = UserProfile
    form_class = UserProfileForm
    template_name = "users/profile_form.html"

    def test_func(self):
        self.object = self.get_object()
        return self.request.user.id == self.object.user.id

    def handle_no_permission(self):
        if self.request.user.username:
            messages.warning(self.request, "You do not have permission to access that")
            return redirect("users:redirect")
        return redirect("home:dashboard")

    def get_object(self):
        id_ = get_object_or_404(User, username=self.kwargs.get("username")).id
        return get_object_or_404(UserProfile, user_id=id_)

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        ctx["cancel_link"] = reverse("users:user_detail", kwargs={"username": self.request.user.username})
        return ctx

    def get_success_url(self):
        messages.success(
            self.request,
            "Successfully updated your profile",
            extra_tags="alert-success",
        )
        return reverse("users:user_detail", kwargs={"username": self.request.user.username})


userprofile_update_view = UserProfileUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    """
    Redirect to the details view for an individual :model:`users.User`.

    **Context**

    ``username``
        Username of the current user

    **Template**

    :template:`None`
    """

    permanent = False

    def get_redirect_url(self):
        return reverse("users:user_detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()


class GhostwriterPasswordChangeView(LoginRequiredMixin, PasswordChangeView):
    """
    Update an existing password for individual :model:`users.User`.

    **Template**

    :template:`account/password_change.html`
    """

    def get_success_url(self):
        messages.success(
            self.request,
            "Your password was successfully updated!",
            extra_tags="alert-success",
        )
        return reverse_lazy("users:user_detail", kwargs={"username": self.request.user.username})


account_change_password = GhostwriterPasswordChangeView.as_view()


class GhostwriterPasswordSetFromKeyView(PasswordResetFromKeyView):  # pragma: no cover
    """
    Reset the password for individual :model:`users.User`.

    **Template**

    :template:`account/password_reset_from_key.html`
    """

    def get_success_url(self):
        return reverse_lazy("account_login")


account_reset_password_from_key = GhostwriterPasswordSetFromKeyView.as_view()

ghostwriter/users/templates/users/profile.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}
{% load custom_tags %}

{% block pagetitle %}User Profile{% endblock %}

{% block breadcrumbs %}
    <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'home:dashboard' %}">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">Your Profile</li>
        </ul>
    </nav>
{% endblock %}

{% block content %}
    <!-- User's Avatar -->
    <a href="{% url 'users:userprofile_update' request.user.username %}">
        <img class="avatar" src="{{ user.userprofile.avatar_url }}" alt="Avatar">
    </a>

    <!-- Users Profile Section -->
    <div class="container profile-container mt-4">
        <div class="row align-items-center text-left text-left">
            <div class="col-sm">
                <p class="bold icon user-icon">Full Name</p>
            </div>
            <div class="col-sm">
                <p class="text-center">{% if user.name %}{{ user.name }}{% else %}Missing Full Name{% endif %}</p>
            </div>
        </div>

        <div class="row align-items-center text-left">
            <div class="col-sm">
                <p class="bold icon user-icon-ninja">Username</p>
            </div>
            <div class="col-sm">
                <p class="text-center">{{ user.username }}</p>
            </div>
        </div>

        <div class="row align-items-center text-left">
            <div class="col-sm">
                <p class="bold icon email-icon">Email</p>
            </div>
            <div class="col-sm">
                <p class="text-center">{{ user.email }}</p>
            </div>
        </div>

        <div class="row align-items-center text-left">
            <div class="col-sm">
                <p class="bold icon phone-icon">Phone</p>
            </div>
            <div class="col-sm">
                <p class="text-center">{% if user.phone %}{{ user.phone }}{% else %}Unavailable{% endif %}</p>
            </div>
        </div>

        <div class="row align-items-center text-left">
            <div class="col-sm">
                <p class="bold icon globe-icon">Timezone</p>
            </div>
            <div class="col-sm">
                <p class="text-center">{{ user.timezone }}</p>
            </div>
        </div>

        {% if request.user == user %}
            <div class="row align-items-center text-left">
                <div class="col-sm">
                    <p class="bold icon user-role-icon">Role</p>
                </div>
                <div class="col-sm">
                    <p class="text-center">
                        {{ user.role|capfirst }}
                    </p>
                </div>
            </div>

            <div class="row align-items-center text-left">
                <div class="col-sm">
                    <p class="bold icon access-icon">Access</p>
                </div>
                <div class="col-sm">
                    <p class="text-center">
                        {% if user.is_superuser %}Superuser{% elif user.is_staff %}Staff{% else %}Normal User{% endif %}
                    </p>
                </div>
            </div>

            {% if user|get_groups %}
                <div class="row align-items-center text-left">
                    <div class="col-sm">
                        <p class="bold icon groups-icon">Groups</p>
                    </div>
                    <div class="col-sm">
                        <p class="text-center">
                            {{ user|get_groups }}
                        </p>
                    </div>
                </div>
            {% endif %}
        {% endif %}
    </div>

    <!-- Account Information Update -->
    {% if request.user == user %}
        <h4 class="icon user-edit-icon pt-4">Update Account Details</h4>
        <hr>

        <div class="btn-group" role="group" aria-label="profile-mgmt">
            <a class="btn btn-primary" href="{% url 'account_change_password' %}">Change Password</a>
            <a class="btn btn-secondary" href="{% url 'users:user_update' request.user.username %}">Update Personal Information</a>
            <a class="btn btn-info" href="{% url 'users:userprofile_update' request.user.username %}">Update Avatar</a>
        </div>

        <div class="col-md-12 pt-4 d-flex text-center position-relative justify-content-center">
            <form class="form-inline">
              <div class="form-group">

                <label class="switch position-absolute start-0" >
                    <input id="js-hide-expired" type="checkbox">
                    <span class="slider round hide-expired-slider"></span>
                </label>

                <h4 class="icon user-secret-icon m-0 align-middle">API Tokens</h4>

                <a class="icon add-icon btn btn-primary float-right col-2 position-absolute end-0" href="{% url 'api:ajax_create_token' %}">Create</a>
              </div>
            </form>
        </div>
        <hr>


        {% if user.apikey_set.get_usable_keys %}
            <table id="tokenTable" class="tablesorter table-sm table-hover">
                <thead>
                    <th class="align-middle">Name</th>
                    <th class="align-middle">Added</th>
                    <th class="align-middle">Expires</th>
                    <th class="align-middle sorter-false"></th>
                </thead>
                {% for key in user.apikey_set.get_usable_keys %}
                    <tr>
                        <td class="align-middle">{{ key.name }}</td>
                        <td class="align-middle">{{ key.created|date:"d M Y @ H:i:s e" }}</td>
                        {% if key.has_expired %}
                            <td class="align-middle burned js-expired-token">{{ key.expiry_date|date:"d M Y @ H:i:s e" }}</td>
                        {% else %}
                            <td class="align-middle">
                                {% if key.expiry_date %}
                                    {{ key.expiry_date|date:"d M Y @ H:i:s e" }}
                                {% else %}
                                    Never
                                {% endif %}
                            </td>
                        {% endif %}
                        <td>
                            <a id="token-revoke-button-{{ key.id }}" class="btn btn-danger js-confirm-revoke" data-toggle="modal" data-target="#confirm-revoke-modal" href="javascript:void(0);" revoke-target-csrftoken="{{ csrf_token }}" revoke-target-url="{% url 'api:ajax_revoke_token' key.id%}" revoke-target-id="{{ key.id }}">
                                Revoke
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </table>
        {% else %}
            <div class="alert alert-secondary mt-3">You have no tokens yet. You can create one with the "Create" button up above.</div>
        {% endif %}
    {% endif %}
{% endblock %}

{% block morescripts %}
    <!-- jQuery Tablesorter Script -->
    <script>
        $(document).ready(function()  {
            $("#tokenTable").tablesorter(
                            {
                                cssAsc: 'down',
                                cssDesc: 'up',
                                cssNone: 'none',
                                headers: {
                                    1: {sorter: 'shortDate'},
                                    2: {sorter: 'shortDate'}
                                },
                            }
                        );
            $('.tablesorter').trigger('update');
        });
    </script>

    <!-- Hide and Show Expired Token Table Rows -->
    <script>
        $(function () {
            $('#js-hide-expired').change(function () {
                var hideCheckbox = $('#js-hide-expired');
                $('.js-expired-token').each(function() {
                    if (hideCheckbox.prop('checked')) {
                        $(this).closest('tr').fadeOut(500);
                    } else {
                        $(this).closest('tr').fadeIn(500);
                    }
                });
            }).change();
        });
    </script>

    <script>
        $(document).ready(function(){
            $('#confirm-token-modal').modal('show');
        });
    </script>

    {% for message in messages %}
        {% if "api-token" in message.tags %}
            <div class="modal" id="confirm-token-modal" data-backdrop="static" data-keyboard="false" tabindex="-1" caller-id="" role="dialog" aria-labelledby="confirm-token-modal-label" aria-hidden="false">
                <div class="modal-dialog token-modal" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Your New Token</h5>
                    </div>
                    <div class="modal-body confirm-token">
                        <code>{{ message|linebreaks }}</code>
                    </div>
                    <div class="modal-footer">
                        <p class="start-0 position-absolute pl-2">Please store it somewhere safe; you will not be able to see it again!</p>
                        <button type="button" class="btn btn-danger" data-dismiss="modal">I Saved It</button>
                    </div>
                </div>
                </div>
            </div>
        {% endif %}
    {% endfor %}

    {% comment %} Include the reusable revoke confirmation modal and related scripts {% endcomment %}
    {% include "confirm_revoke_modal.html" %}
{% endblock %}

ghostwriter/users/templates/users/profile_form.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}

{% block pagetitle %}User Profile{% endblock %}

{% block breadcrumbs %}
    <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'home:dashboard' %}">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="{% url 'users:user_detail' request.user.username %}">Your Profile</a></li>
            <li class="breadcrumb-item active" aria-current="page">Profile Form</li>
        </ul>
    </nav>
{% endblock %}

{% block content %}
    <!-- Current Avatar -->
    <img class="avatar" src="{{ user.userprofile.avatar_url }}" alt="User Image">

    <!-- Form Error Section -->
    {% if form.errors %}
        <script>
            {% for field in form %}
                {% for error in field.errors %}
                    displayToastTop({type:'error', string:'{{ error }}', context:'form'});
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                displayToastTop({type:'error', string:'{{ error }}', context:'form'});
            {% endfor %}
        </script>
    {% endif %}

    <!-- Avatar Upload Form -->
    {% crispy form form.helper %}
{% endblock %}

{% block morescripts %}
{% endblock %}