config/urls.py
"""This contains all of the base URL mappings used by Ghostwriter."""

# Django Imports
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path, re_path
from django.views import defaults as default_views
from django.views.generic import RedirectView

# Ghostwriter Libraries
from ghostwriter.home.views import protected_serve
from ghostwriter.users.views import (
    account_change_password,
    account_reset_password_from_key,
)

urlpatterns = [
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("ghostwriter.users.urls", namespace="users")),
    path("home/", include("ghostwriter.home.urls", namespace="home")),
    path(
        "accounts/password/change/",
        account_change_password,
        name="account_change_password",
    ),
    re_path(
        r"^accounts/password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
        account_reset_password_from_key,
        name="account_reset_password_from_key",
    ),
    path("accounts/", include("allauth.urls")),
    # path("accounts/", include("django.contrib.auth.urls")),
    path("rolodex/", include("ghostwriter.rolodex.urls", namespace="rolodex")),
    path("shepherd/", include("ghostwriter.shepherd.urls", namespace="shepherd")),
    path("reporting/", include("ghostwriter.reporting.urls", namespace="reporting")),
    path("", RedirectView.as_view(pattern_name="home:dashboard"), name="home"),
    path("oplog/", include("ghostwriter.oplog.urls", namespace="oplog")),
    re_path(
        r"^%s(?P<path>.*)$" % settings.MEDIA_URL[1:],
        protected_serve,
        {"document_root": settings.MEDIA_ROOT},
    ),
    path("api/", include("ghostwriter.api.urls", namespace="api")),
    path("status/", include("ghostwriter.status.urls", namespace="status")),
    # Add additional custom paths below this line...
    # Your stuff: custom urls includes go here
]

if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:

        import debug_toolbar  # noqa isort:skip

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

ghostwriter/home/urls.py
"""This contains all of the URL mappings used by the Home application."""

# Django Imports
from django.urls import path
from django.views.decorators.csrf import csrf_exempt

# Ghostwriter Libraries
from ghostwriter.home import views

app_name = "home"

# URLs for the basic views
urlpatterns = [
    path("", views.Dashboard.as_view(), name="dashboard"),
    path("management/", views.Management.as_view(), name="management"),
]

# URLs for AJAX test functions
urlpatterns += [
    path(
        "ajax/management/test/aws",
        views.TestAWSConnection.as_view(),
        name="ajax_test_aws",
    ),
    path(
        "ajax/management/test/do",
        views.TestDOConnection.as_view(),
        name="ajax_test_do",
    ),
    path(
        "ajax/management/test/namecheap",
        views.TestNamecheapConnection.as_view(),
        name="ajax_test_namecheap",
    ),
    path(
        "ajax/management/test/slack",
        views.TestSlackConnection.as_view(),
        name="ajax_test_slack",
    ),
    path(
        "ajax/management/test/virustotal",
        views.TestVirusTotalConnection.as_view(),
        name="ajax_test_virustotal",
    ),
    path(
        "ajax/session/update",
        csrf_exempt(views.update_session),
        name="ajax_update_session",
    ),
]

ghostwriter/home/forms.py
"""This contains all of the forms used by the Home application."""

# Django Imports
from django import forms
from django.contrib.auth import get_user_model

# 3rd Party Libraries
from crispy_forms.helper import FormHelper
from crispy_forms.layout import HTML, ButtonHolder, Div, Layout, Submit

# Ghostwriter Libraries
from ghostwriter.home.models import UserProfile


class UserProfileForm(forms.ModelForm):
    """
    Upload user profile avatar for an individual :model:`home.UserProfile`.
    """

    class Meta:
        model = UserProfile
        exclude = ("user",)
        widgets = {
            "avatar": forms.FileInput(attrs={"class": "form-control"}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["avatar"].label = ""
        self.fields["avatar"].widget.attrs["class"] = "custom-file-input"
        self.helper = FormHelper()
        self.helper.form_method = "post"
        self.helper.form_class = "newitem"
        self.helper.attrs = {"enctype": "multipart/form-data"}
        self.helper.form_show_labels = False
        self.helper.layout = Layout(
            HTML(
                """
                <h4 class="icon avatar-upload-icon">Avatar Upload</h4>
                <p>Your new avatar should be a square (equal height and width) for the best looking results.</p>
                """
            ),
            Div(
                "avatar",
                HTML(
                    """
                    <label id="filename" class="custom-file-label" for="customFile">Choose an Avatar Image File...</label>
                    """
                ),
                css_class="custom-file col-md-8",
            ),
            ButtonHolder(
                Submit("submit", "Submit", css_class="btn btn-primary col-md-4"),
                HTML(
                    """
                    <button onclick="window.location.href='{{ cancel_link }}'" class="btn btn-outline-secondary col-md-4" type="button">Cancel</button>
                    """
                ),
            ),
        )


class SignupForm(forms.ModelForm):
    """
    Create a new :model:`users.User`.
    """

    class Meta:
        model = get_user_model()
        fields = [
            "name",
        ]

    def signup(self, request, user):  # pragma: no cover
        user.name = self.cleaned_data["name"]
        user.save()

ghostwriter/home/views.py
"""This contains all of the views used by the Home application."""

# Standard Libraries
import logging

# Django Imports
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Q
from django.http import HttpResponseNotAllowed, JsonResponse
from django.shortcuts import redirect, render
from django.views.generic.edit import View
from django.views.static import serve

# 3rd Party Libraries
from django_q.models import Task
from django_q.tasks import async_task

# Ghostwriter Libraries
from ghostwriter.modules.health_utils import DjangoHealthChecks
from ghostwriter.reporting.models import ReportFindingLink
from ghostwriter.rolodex.models import ProjectAssignment

User = get_user_model()

# Using __name__ resolves to ghostwriter.home.views
logger = logging.getLogger(__name__)


##################
# View Functions #
##################


@login_required
def update_session(request):
    """
    Update the requesting user's session variable based on ``session_data`` in POST.
    """
    if request.method == "POST":
        req_data = request.POST.get("session_data", None)
        if req_data:
            if req_data == "sidebar":
                if "sidebar" in request.session.keys():
                    request.session["sidebar"]["sticky"] ^= True
                else:
                    request.session["sidebar"] = {}
                    request.session["sidebar"]["sticky"] = True
            request.session.save()
        data = {
            "result": "success",
            "message": "Session updated",
        }
        return JsonResponse(data)

    return HttpResponseNotAllowed(["POST"])


@login_required
def protected_serve(request, path, document_root=None, show_indexes=False):
    """
    Serve static files from ``MEDIA_ROOT`` for authenticated requests.
    """
    return serve(request, path, document_root, show_indexes)


class Dashboard(LoginRequiredMixin, View):
    """
    Display the home page.

    **Context**

    ``user_projects``
        All :model:`reporting.ProjectAssignment` for current :model:`users.User`
    ``active_projects``
        All :model:`reporting.ProjectAssignment` for active :model:`rolodex.Project` and current :model:`users.User`
    ``recent_tasks``
        Five most recent :model:`django_q.Task` entries
    ``user_tasks``
        Incomplete :model:`reporting.ReportFindingLink` for current :model:`users.User`
    ``system_health``
        Current system health based on :func:`ghostwriter.modules.health_utils.DjangoHealthChecks`

    **Template**

    :template:`index.html`
    """

    def get(self, request, *args, **kwargs):
        # Get the most recent :model:`django_q.Task` entries
        recent_tasks = Task.objects.all()[:5]
        # Get incomplete :model:`reporting.ReportFindingLink` for current :model:`users.User`
        user_tasks = (
            ReportFindingLink.objects.select_related("report", "report__project")
            .filter(
                Q(assigned_to=request.user) & Q(report__complete=False) & Q(complete=False)
            )
            .order_by("report__project__end_date")[:10]
        )
        # Get active :model:`reporting.ProjectAssignment` for current :model:`users.User`
        user_projects = ProjectAssignment.objects.select_related(
            "project", "project__client", "role"
        ).filter(operator=request.user)
        # Get future :model:`reporting.ProjectAssignment` for current :model:`users.User`
        active_project = ProjectAssignment.objects.select_related(
            "project", "project__client", "role"
        ).filter(Q(operator=request.user) & Q(project__complete=False))
        # Get system status
        system_health = "OK"
        try:
            healthcheck = DjangoHealthChecks()
            db_status = healthcheck.get_database_status()
            cache_status = healthcheck.get_cache_status()
            if not db_status["default"] or not cache_status["default"]:
                system_health = "WARNING"
        except Exception:
            system_health = "ERROR"

        # Assemble the context dictionary to pass to the dashboard
        context = {
            "user_projects": user_projects,
            "active_projects": active_project,
            "recent_tasks": recent_tasks,
            "user_tasks": user_tasks,
            "system_health": system_health,
        }
        # Render the HTML template index.html with the data in the context variable
        return render(request, "index.html", context=context)

class Management(LoginRequiredMixin, UserPassesTestMixin, View):
    """
    Display the current Ghostwriter settings.

    **Context**

    ``timezone``
        The current value of ``settings.TIME_ZONE``

    **Template**

    :template:`home/management.html`
    """

    def test_func(self):
        return self.request.user.is_staff

    def handle_no_permission(self):
        messages.error(self.request, "You do not have permission to access that")
        return redirect("home:dashboard")

    def get(self, request, *args, **kwargs):
        context = {
            "timezone": settings.TIME_ZONE,
        }
        return render(request, "home/management.html", context=context)


class TestAWSConnection(LoginRequiredMixin, UserPassesTestMixin, View):
    """
    Create an individual :model:`django_q.Task` under group ``AWS Test`` with
    :task:`shepherd.tasks.test_aws_keys` to test AWS keys in
    :model:`commandcenter.CloudServicesConfiguration`.
    """

    def test_func(self):
        return self.request.user.is_staff

    def handle_no_permission(self):
        messages.error(self.request, "You do not have permission to access that")
        return redirect("home:dashboard")

    def post(self, request, *args, **kwargs):
        # Add an async task grouped as ``AWS Test``
        result = "success"
        try:
            async_task(
                "ghostwriter.shepherd.tasks.test_aws_keys",
                self.request.user,
                group="AWS Test",
            )
            message = "AWS access key test has been successfully queued"
        except Exception:  # pragma: no cover
            result = "error"
            message = "AWS access key test could not be queued"

        data = {
            "result": result,
            "message": message,
        }
        return JsonResponse(data)


class TestDOConnection(LoginRequiredMixin, UserPassesTestMixin, View):
    """
    Create an individual :model:`django_q.Task` under group ``Digital Ocean Test`` with
    :task:`shepherd.tasks.test_digital_ocean` to test the Digital Ocean API key stored in
    :model:`commandcenter.CloudServicesConfiguration`.
    """

    def test_func(self):
        return self.request.user.is_staff

    def handle_no_permission(self):
        messages.error(self.request, "You do not have permission to access that")
        return redirect("home:dashboard")

    def post(self, request, *args, **kwargs):
        # Add an async task grouped as ``Digital Ocean Test``
        result = "success"
        try:
            async_task(
                "ghostwriter.shepherd.tasks.test_digital_ocean",
                self.request.user,
                group="Digital Ocean Test",
            )
            message = "Digital Ocean API key test has been successfully queued"
        except Exception:  # pragma: no cover
            result = "error"
            message = "Digital Ocean API key test could not be queued"

        data = {
            "result": result,
            "message": message,
        }
        return JsonResponse(data)


class TestNamecheapConnection(LoginRequiredMixin, UserPassesTestMixin, View):
    """
    Create an individual :model:`django_q.Task` under group ``Namecheap Test`` with
    :task:`shepherd.tasks.test_namecheap` to test the Namecheap API configuration stored
    in :model:`commandcenter.NamecheapConfiguration`.
    """

    def test_func(self):
        return self.request.user.is_staff

    def handle_no_permission(self):
        messages.error(self.request, "You do not have permission to access that")
        return redirect("home:dashboard")

    def post(self, request, *args, **kwargs):
        # Add an async task grouped as ``Namecheap Test``
        result = "success"
        try:
            async_task(
                "ghostwriter.shepherd.tasks.test_namecheap",
                self.request.user,
                group="Namecheap Test",
            )
            message = "Namecheap API test has been successfully queued"
        except Exception:  # pragma: no cover
            result = "error"
            message = "Namecheap API test could not be queued"

        data = {
            "result": result,
            "message": message,
        }
        return JsonResponse(data)


class TestSlackConnection(LoginRequiredMixin, UserPassesTestMixin, View):
    """
    Create an individual :model:`django_q.Task` under group ``Slack Test`` with
    :task:`shepherd.tasks.test_slack_webhook` to test the Slack Webhook configuration
    stored in :model:`commandcenter.SlackConfiguration`.
    """

    def test_func(self):
        return self.request.user.is_staff

    def handle_no_permission(self):
        messages.error(self.request, "You do not have permission to access that")
        return redirect("home:dashboard")

    def post(self, request, *args, **kwargs):
        # Add an async task grouped as ``Slack Test``
        result = "success"
        try:
            async_task(
                "ghostwriter.shepherd.tasks.test_slack_webhook",
                self.request.user,
                group="Slack Test",
            )
            message = "Slack Webhook test has been successfully queued"
        except Exception:  # pragma: no cover

ghostwriter/home/templates/home/management.html
{% extends "base_generic.html" %}

{% load settings_tags %}

{% block pagetitle %}Manage API Access{% endblock %}

{% block breadcrumbs %}
    <nav aria-label="breadcrumb" style="padding-left: 20px;">
        <ul class="breadcrumb" style="margin: 0;">
            <li class="breadcrumb-item"><a href="{% url 'home:dashboard' %}">Dashboard</a></li>
            <li class="breadcrumb-item active" aria-current="page">Review Configuration</li>
        </ul>
    </nav>
{% endblock %}

{% block content %}
    {% comment %} Get the current configuration from the singleton models {% endcomment %}
    {% get_solo "commandcenter.CompanyInformation" as company_config %}
    {% get_solo "commandcenter.CloudServicesConfiguration" as cloud_config %}
    {% get_solo "commandcenter.NamecheapConfiguration" as namecheap_config %}
    {% get_solo "commandcenter.ReportConfiguration" as report_config %}
    {% get_solo "commandcenter.SlackConfiguration" as slack_config %}
    {% get_solo "commandcenter.VirusTotalConfiguration" as vt_config %}

    <h2>API & Notification Configurations</h2>
    <p>These settings are managed in the Django administration panel under the <em>Command Center</em> application.</p>
    <p>To change the <em>Timezone</em>, edit the application's settings file and restart the server.</p>

    <table class="table table-responsive-lg table-borderless table-config">
        <!-- General Section -->
        <tr>
            <th class="text-left icon gears-icon">General Settings</th>
            <th></th>
        </tr>
        <tr>
            <td class="text-left icon clock-icon">Timezone Time</td>
            <td class="text-justify">{{ timezone }}</td>
        </tr>
        <tr>
            <td class="text-left icon client-icon">Company Name</td>
            <td class="text-justify">{{ company_config.company_name }}</td>
        </tr>
        <tr>
            <td class="text-left icon twitter-icon">Twitter</td>
            <td class="text-justify">{{ company_config.company_twitter }}</td>
        </tr>
        <tr>
            <td class="text-left icon email-icon">Email</td>
            <td class="text-justify">{{ company_config.company_email }}</td>
        </tr>

        <!-- Spacer -->
        <tr>
            <td class="text-justify">&nbsp;</td>
            <td class="text-justify">&nbsp;</td>
        </tr>

        <!-- Domain Health Section -->
        <tr>
            <th class="text-left icon heartbeat-icon">Domain Health Checks</th>
            <th></th>
        </tr>
        <tr>
            <td class="text-left icon vt-icon">VirusTotal API Key</td>
            {% if vt_config.enable %}
                <td class="text-justify">{{ vt_config.sanitized_api_key }}</td>
            {% else %}
                <td class="text-justify">Disabled</td>
            {% endif %}
        </tr>
        <tr>
            <td class="text-left icon sleep-icon">Sleep Time</td>
            <td class="text-justify">{{ vt_config.sleep_time }} seconds</td>
        </tr>

        <!-- Spacer -->
        <tr>
            <td class="text-justify">&nbsp;</td>
            <td class="text-justify">&nbsp;</td>
        </tr>

        <!-- Registrar Section -->
        <tr>
            <th class="text-left icon sync-icon">Domain Registrar API</th>
            <th></th>
        </tr>
        {% if namecheap_config.enable %}
            <tr>
                <td class="text-left icon toggle-on-icon">Namecheap API Enabled</td>
                <td class="text-justify">{{ namecheap_config.enable }}</td>
            </tr>
            <tr>
                <td class="text-left icon laptop-icon">Namecheap Whitelisted IP</td>
                <td class="text-justify">{{ namecheap_config.client_ip }}</td>
            </tr>
            <tr>
                <td class="text-left icon key-icon">Namecheap API Key</td>
                <td class="text-justify">{{ namecheap_config.sanitized_api_key }}</td>
            </tr>
            <tr>
                <td class="text-left icon user-icon">Namecheap Username</td>
                <td class="text-justify">{{ namecheap_config.username }}</td>
            </tr>
            <tr>
                <td class="text-left icon user-gear-icon">Namecheap API Username</td>
                <td class="text-justify">{{ namecheap_config.api_username }}</td>
            </tr>
            <tr>
                <td class="text-left icon hash-icon">Namecheap Page Size</td>
                <td class="text-justify">{{ namecheap_config.page_size }}</td>
            </tr>
        {% else %}
            <tr>
                <td class="text-left icon toggle-off-icon">Namecheap API Enabled</td>
                <td class="text-justify">Disabled</td>
            </tr>
        {% endif %}

        <!-- Spacer -->
        <tr>
            <td class="text-justify">&nbsp;</td>
            <td class="text-justify">&nbsp;</td>
        </tr>

        <!-- Cloud Monitor Section -->
        <tr>
            <th class="text-left icon cloud-icon">Cloud Services</th>
            <th></th>
        </tr>
        {% if cloud_config.enable %}
            <tr>
                <td class="text-left icon toggle-on-icon">Cloud Monitoring Enabled</td>
                <td class="text-justify">{{ cloud_config.enable }}</td>
            </tr>
            <tr>
                <td class="text-left icon aws-icon">AWS Access Key</td>
                <td class="text-justify">{{ cloud_config.sanitized_aws_key }}</td>
            </tr>
            <tr>
                <td class="text-left icon aws-icon">AWS Access Key Secret</td>
                <td class="text-justify">{{ cloud_config.sanitized_aws_secret }}</td>
            </tr>
            <tr>
                <td class="text-left icon do-icon">Digital Ocean API Key</td>
                <td class="text-justify">{{ cloud_config.sanitized_do_api_key }}</td>
            </tr>
        {% else %}
            <tr>
                <td class="text-left icon toggle-off-icon">Cloud Monitoring Enabled</td>
                <td class="text-justify">Disabled</td>
            </tr>
        {% endif %}

        <!-- Spacer -->
        <tr>
            <td class="text-justify">&nbsp;</td>
            <td class="text-justify">&nbsp;</td>
        </tr>

        <!-- Notification Section -->
        <tr>
            <th class="text-left icon notification-icon">Notifications</th>
            <th></th>
        </tr>
        {% if slack_config.enable %}
            <tr>
                <td class="text-left icon toggle-on-icon">Slack Enabled</td>
                <td class="text-justify">{{ slack_config.enable }}</td>
            </tr>
            <tr>
                <td class="text-left icon slack-icon">Slack WebHook</td>
                <td class="text-justify">{{ slack_config.sanitized_webhook }}</td>
            </tr>
            <tr>
                <td class="text-left icon slack-icon">Slack Bot Name</td>
                <td class="text-justify">{{ slack_config.slack_username }}</td>
            </tr>
            <tr>
                <td class="text-left icon slack-icon">Slack Bot Avatar</td>
                <td class="text-justify">{{ slack_config.slack_emoji }}</td>
            </tr>
            <tr>
                <td class="text-left icon slack-icon">Global Slack Channel</td>
                <td class="text-justify">{{ slack_config.slack_channel }}</td>
            </tr>
            <tr>
                <td class="text-left icon slack-icon">Slack Target</td>
                <td class="text-justify">{{ slack_config.slack_alert_target }}</td>
            </tr>
        {% else %}
            <tr>
                <td class="text-left icon toggle-off-icon">Slack Enabled</td>
                <td class="text-justify">Disabled</td>
            </tr>
        {% endif %}
    </table>

    <h6>Test Configurations</h6>
    <hr />

    <div class="form-group">
    <div class="btn-toolbar justify-content-center" role="toolbar" aria-label="Config Test Toolbar">
        <div class="btn-group mr-2" role="group" aria-label="Cloud Tests">
            <button type="submit" class="js-queue-task btn btn-primary" queue-task-url="{% url 'home:ajax_test_aws' %}" queue-task-csrf-token="{{ csrf_token }}">Test AWS Keys</button>
            <button type="submit" class="js-queue-task btn btn-primary" queue-task-url="{% url 'home:ajax_test_do' %}" queue-task-csrf-token="{{ csrf_token }}">Test Digital Ocean</button>
        </div>

        <div class="btn-group mr-2" role="group" aria-label="API Tests">
                <button class="js-queue-task btn btn-primary" queue-task-url="{% url 'home:ajax_test_namecheap' %}" queue-task-csrf-token="{{ csrf_token }}">Test Namecheap API</button>
                <button class="js-queue-task btn btn-primary" queue-task-url="{% url 'home:ajax_test_virustotal' %}" queue-task-csrf-token="{{ csrf_token }}">Test VirusTotal API</button>
        </div>

        <div class="btn-group" role="group" aria-label="Notification Tests">
                <button class="js-queue-task btn btn-primary" queue-task-url="{% url 'home:ajax_test_slack' %}" queue-task-csrf-token="{{ csrf_token }}">Test Slack Webhook</button>
        </div>
    </div>
    </div>
{% endblock %}

{% block morescripts %}
    <!-- Queue Tasks with AJAX -->
    <script>
        $('.js-queue-task').each(function(index) {
            $(this).on('click', function (event) {
                // Prevent default browser behavior for a form submission
                event.preventDefault();
                // Get the URL from form attribute
                var url = $(this).attr('queue-task-url');
                var csrf_token = $(this).attr('queue-task-csrf-token');
                // Send AJAX POST request
                $.ajax({
                    url: url,
                    type: 'POST',
                    dataType: 'json',
                    data: {
                        csrfmiddlewaretoken: csrf_token,
                    },
                    success: function (data) {
                        if (data['result'] == 'success') {
                            // Do something
                        }
                        if (data['message']) {
                            displayToastTop({type:data['result'], string:data['message'], title:'Task Update'});
                        }
                    }
                });
            });
        });
    </script>
{% endblock %}