config/urls.py
"""This contains all of the base URL mappings used by Ghostwriter."""

# Django Imports
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import include, path, re_path
from django.views import defaults as default_views
from django.views.generic import RedirectView

# Ghostwriter Libraries
from ghostwriter.home.views import protected_serve
from ghostwriter.users.views import (
    account_change_password,
    account_reset_password_from_key,
)

urlpatterns = [
    path("admin/doc/", include("django.contrib.admindocs.urls")),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("ghostwriter.users.urls", namespace="users")),
    path("home/", include("ghostwriter.home.urls", namespace="home")),
    path(
        "accounts/password/change/",
        account_change_password,
        name="account_change_password",
    ),
    re_path(
        r"^accounts/password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
        account_reset_password_from_key,
        name="account_reset_password_from_key",
    ),
    path("accounts/", include("allauth.urls")),
    # path("accounts/", include("django.contrib.auth.urls")),
    path("rolodex/", include("ghostwriter.rolodex.urls", namespace="rolodex")),
    path("shepherd/", include("ghostwriter.shepherd.urls", namespace="shepherd")),
    path("reporting/", include("ghostwriter.reporting.urls", namespace="reporting")),
    path("", RedirectView.as_view(pattern_name="home:dashboard"), name="home"),
    path("oplog/", include("ghostwriter.oplog.urls", namespace="oplog")),
    re_path(
        r"^%s(?P<path>.*)$" % settings.MEDIA_URL[1:],
        protected_serve,
        {"document_root": settings.MEDIA_ROOT},
    ),
    path("api/", include("ghostwriter.api.urls", namespace="api")),
    path("status/", include("ghostwriter.status.urls", namespace="status")),
    # Add additional custom paths below this line...
    # Your stuff: custom urls includes go here
]

if settings.DEBUG:
    # Static file serving when using Gunicorn + Uvicorn for local web socket development
    urlpatterns += staticfiles_urlpatterns()

    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:

        import debug_toolbar  # noqa isort:skip

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

ghostwriter/reporting/urls.py
"""This contains all of the URL mappings used by the Reporting application."""

# Django Imports
from django.urls import path

from . import views

app_name = "reporting"

# URLs for the basic views
urlpatterns = [
    path("", views.index, name="index"),
    path("findings/", views.findings_list, name="findings"),
    path("reports/", views.reports_list, name="reports"),
    path("templates/", views.ReportTemplateListView.as_view(), name="templates"),
    path("reports/archive", views.archive_list, name="archived_reports"),
    path(
        "reports/archive/download/<int:pk>/",
        views.download_archive,
        name="download_archive",
    ),
]

# URLs for AJAX requests – deletion and toggle views
urlpatterns += [
    path(
        "ajax/report/finding/order",
        views.ajax_update_report_findings,
        name="update_report_findings",
    ),
    path(
        "ajax/report/activate/<int:pk>",
        views.ReportActivate.as_view(),
        name="ajax_activate_report",
    ),
    path(
        "ajax/report/finding/status/<int:pk>/<str:status>",
        views.ReportFindingStatusUpdate.as_view(),
        name="ajax_set_finding_status",
    ),
    path(
        "ajax/report/status/toggle/<int:pk>",
        views.ReportStatusToggle.as_view(),
        name="ajax_toggle_report_status",
    ),
    path(
        "ajax/report/delivery/<int:pk>",
        views.ReportDeliveryToggle.as_view(),
        name="ajax_toggle_report_delivery",
    ),
    path(
        "ajax/report/note/delete/<int:pk>",
        views.LocalFindingNoteDelete.as_view(),
        name="ajax_delete_local_finding_note",
    ),
    path(
        "ajax/finding/note/delete/<int:pk>",
        views.FindingNoteDelete.as_view(),
        name="ajax_delete_finding_note",
    ),
    path(
        "ajax/finding/assign/<int:pk>",
        views.AssignFinding.as_view(),
        name="ajax_assign_finding",
    ),
    path(
        "ajax/finding/delete/<int:pk>",
        views.ReportFindingLinkDelete.as_view(),
        name="ajax_delete_local_finding",
    ),
    path(
        "ajax/report/template/swap/<int:pk>",
        views.ReportTemplateSwap.as_view(),
        name="ajax_swap_report_template",
    ),
    path(
        "ajax/report/template/lint/<int:pk>",
        views.ReportTemplateLint.as_view(),
        name="ajax_lint_report_template",
    ),
    path(
        "ajax/report/template/lint/results/<int:pk>",
        views.UpdateTemplateLintResults.as_view(),
        name="ajax_update_template_lint_results",
    ),
]

# URLs for creating, updating, and deleting findings
urlpatterns += [
    path("findings/<int:pk>", views.FindingDetailView.as_view(), name="finding_detail"),
    path("findings/create/", views.FindingCreate.as_view(), name="finding_create"),
    path(
        "findings/update/<int:pk>", views.FindingUpdate.as_view(), name="finding_update"
    ),
    path(
        "findings/delete/<int:pk>", views.FindingDelete.as_view(), name="finding_delete"
    ),
    path(
        "findings/notes/create/<int:pk>",
        views.FindingNoteCreate.as_view(),
        name="finding_note_add",
    ),
    path(
        "findings/notes/update/<int:pk>",
        views.FindingNoteUpdate.as_view(),
        name="finding_note_edit",
    ),
]

# URLs for creating, updating, and deleting reports
urlpatterns += [
    path("reports/<int:pk>", views.ReportDetailView.as_view(), name="report_detail"),
    path("reports/create/<int:pk>", views.ReportCreate.as_view(), name="report_create"),
    path(
        "reports/create/",
        views.ReportCreate.as_view(),
        name="report_create_no_project",
    ),
    path("reports/update/<int:pk>", views.ReportUpdate.as_view(), name="report_update"),
    path("reports/delete/<int:pk>", views.ReportDelete.as_view(), name="report_delete"),
    path("reports/archive/<int:pk>", views.archive, name="archive"),
    path("reports/clone/<int:pk>", views.ReportClone.as_view(), name="report_clone"),
    path(
        "reports/create/blank/<int:pk>",
        views.AssignBlankFinding.as_view(),
        name="assign_blank_finding",
    ),
    path(
        "templates/<int:pk>",
        views.ReportTemplateDetailView.as_view(),
        name="template_detail",
    ),
    path(
        "templates/create",
        views.ReportTemplateCreate.as_view(),
        name="template_create",
    ),
    path(
        "templates/update/<int:pk>",
        views.ReportTemplateUpdate.as_view(),
        name="template_update",
    ),
    path(
        "templates/delete/<int:pk>",
        views.ReportTemplateDelete.as_view(),
        name="template_delete",
    ),
    path(
        "templates/download/<int:pk>",
        views.ReportTemplateDownload.as_view(),
        name="template_download",
    ),
]

# URLs for local edits
urlpatterns += [
    path(
        "reports/findings/update/<int:pk>",
        views.ReportFindingLinkUpdate.as_view(),
        name="local_edit",
    ),
    path(
        "reports/evidence/upload/<int:pk>",
        views.EvidenceCreate.as_view(),
        name="upload_evidence",
    ),
    path(
        "reports/evidence/upload/<int:pk>/<str:modal>",
        views.EvidenceCreate.as_view(),
        name="upload_evidence_modal",
    ),
    path(
        "reports/evidence/modal/success",
        views.upload_evidence_modal_success,
        name="upload_evidence_modal_success",
    ),
    path(
        "reports/evidence/<int:pk>",
        views.EvidenceDetailView.as_view(),
        name="evidence_detail",
    ),
    path(
        "reports/evidence/update/<int:pk>",
        views.EvidenceUpdate.as_view(),
        name="evidence_update",
    ),
    path(
        "reports/evidence/delete/<int:pk>",
        views.EvidenceDelete.as_view(),
        name="evidence_delete",
    ),
    path(
        "reports/notes/create/<int:pk>",
        views.LocalFindingNoteCreate.as_view(),
        name="local_finding_note_add",
    ),
    path(
        "reports/notes/update/<int:pk>",
        views.LocalFindingNoteUpdate.as_view(),
        name="local_finding_note_edit",
    ),
    path(
        "reports/findings/convert/<int:pk>",
        views.ConvertFinding.as_view(),
        name="convert_finding",
    ),
]

# URLs for generating reports
urlpatterns += [
    path(
        "reports/<int:pk>/docx/",
        views.GenerateReportDOCX.as_view(),
        name="generate_docx",
    ),
    path(
        "reports/<int:pk>/xlsx/",
        views.GenerateReportXLSX.as_view(),
        name="generate_xlsx",
    ),
    path(
        "reports/<int:pk>/pptx/",
        views.GenerateReportPPTX.as_view(),
        name="generate_pptx",
    ),
    path(
        "reports/<int:pk>/raw/",
        views.GenerateReportJSON.as_view(),
        name="generate_json",
    ),
    path("reports/<int:pk>/all/", views.GenerateReportAll.as_view(), name="generate_all"),
]

# URLs for management functions
urlpatterns += [
    path("export/findings/csv/", views.export_findings_to_csv, name="export_findings_to_csv"),
]

ghostwriter/rolodex/urls.py
"""This contains all of the URL mappings used by the Rolodex application."""

# Django Imports
from django.urls import path

from . import views

app_name = "rolodex"

# URLs for the basic views
urlpatterns = [
    path("", views.index, name="index"),
    path("clients/", views.client_list, name="clients"),
    path("projects/", views.project_list, name="projects"),
]

# URLs for AJAX requests – deletion and toggle views
urlpatterns += [
    path(
        "ajax/codename/roll",
        views.roll_codename,
        name="ajax_roll_codename",
    ),
    path(
        "ajax/project/toggle/<int:pk>",
        views.ProjectStatusToggle.as_view(),
        name="ajax_toggle_project",
    ),
    path(
        "ajax/project/objective/status/<int:pk>",
        views.ProjectObjectiveStatusUpdate.as_view(),
        name="ajax_set_objective_status",
    ),
    path(
        "ajax/project/objective/order",
        views.ajax_update_project_objectives,
        name="ajax_update_objective_order",
    ),
    path(
        "ajax/project/objective/toggle/<int:pk>",
        views.ProjectObjectiveToggle.as_view(),
        name="ajax_toggle_project_objective",
    ),
    path(
        "ajax/project/objective/refresh/<int:pk>",
        views.ProjectObjectiveRefresh.as_view(),
        name="ajax_update_objective_row",
    ),
    path(
        "ajax/project/objective/delete/<int:pk>",
        views.ProjectObjectiveDelete.as_view(),
        name="ajax_delete_project_objective",
    ),
    path(
        "ajax/project/deconfliction/delete/<int:pk>",
        views.DeconflictionDelete.as_view(),
        name="ajax_delete_project_deconfliction",
    ),
    path(
        "ajax/project/assignment/delete/<int:pk>",
        views.ProjectAssignmentDelete.as_view(),
        name="ajax_delete_project_assignment",
    ),
    path(
        "ajax/project/note/delete/<int:pk>",
        views.ProjectNoteDelete.as_view(),
        name="ajax_delete_project_note",
    ),
    path(
        "ajax/client/contact/delete/<int:pk>",
        views.ClientContactDelete.as_view(),
        name="ajax_delete_client_poc",
    ),
    path(
        "ajax/client/note/delete/<int:pk>",
        views.ClientNoteDelete.as_view(),
        name="ajax_delete_client_note",
    ),
    path(
        "ajax/project/refresh/<int:pk>",
        views.update_project_badges,
        name="ajax_update_project_badges",
    ),
    path(
        "ajax/client/refresh/<int:pk>",
        views.update_client_badges,
        name="ajax_update_client_badges",
    ),
    path(
        "ajax/project/target/compromise/<int:pk>",
        views.ProjectTargetToggle.as_view(),
        name="ajax_toggle_project_target",
    ),
    path(
        "ajax/project/target/delete/<int:pk>",
        views.ProjectTargetDelete.as_view(),
        name="ajax_delete_project_target",
    ),
    path(
        "ajax/project/scope/delete/<int:pk>",
        views.ProjectScopeDelete.as_view(),
        name="ajax_delete_project_scope",
    ),
    path(
        "ajax/project/scope/export/<int:pk>",
        views.ProjectScopeExport.as_view(),
        name="ajax_export_project_scope",
    ),
    path(
        "ajax/project/task/create/<int:pk>",
        views.ProjectTaskCreate.as_view(),
        name="ajax_create_project_task",
    ),
    path(
        "ajax/project/task/toggle/<int:pk>",
        views.ProjectTaskToggle.as_view(),
        name="ajax_toggle_project_task",
    ),
    path(
        "ajax/project/task/delete/<int:pk>",
        views.ProjectTaskDelete.as_view(),
        name="ajax_delete_project_task",
    ),
    path(
        "ajax/project/task/update/<int:pk>",
        views.ProjectTaskUpdate.as_view(),
        name="ajax_update_project_task",
    ),
    path(
        "ajax/project/task/refresh/<int:pk>",
        views.ProjectTaskRefresh.as_view(),
        name="ajax_update_objective_tasks",
    ),
]

# URLs for :model:`Client` Class Based Views
urlpatterns += [
    path("clients/<int:pk>", views.ClientDetailView.as_view(), name="client_detail"),
    path("clients/create/", views.ClientCreate.as_view(), name="client_create"),
    path("clients/update/<int:pk>", views.ClientUpdate.as_view(), name="client_update"),
    path("clients/delete/<int:pk>", views.ClientDelete.as_view(), name="client_delete"),
    path(
        "clients/notes/create/<int:pk>",
        views.ClientNoteCreate.as_view(),
        name="client_note_add",
    ),
    path(
        "clients/notes/update/<int:pk>",
        views.ClientNoteUpdate.as_view(),
        name="client_note_edit",
    ),
]

# URLs for :model:`Project` Class Based Views
urlpatterns += [
    path("projects/<int:pk>", views.ProjectDetailView.as_view(), name="project_detail"),
    path(
        "projects/create",
        views.ProjectCreate.as_view(),
        name="project_create_no_client",
    ),
    path(
        "projects/create/<int:pk>", views.ProjectCreate.as_view(), name="project_create"
    ),
    path(
        "projects/update/<int:pk>",
        views.ProjectUpdate.as_view(),
        name="project_update",
    ),
    path(
        "projects/delete/<int:pk>",
        views.ProjectDelete.as_view(),
        name="project_delete",
    ),
    path(
        "projects/notes/create/<int:pk>",
        views.ProjectNoteCreate.as_view(),
        name="project_note_add",
    ),
    path(
        "projects/notes/update/<int:pk>",
        views.ProjectNoteUpdate.as_view(),
        name="project_note_edit",
    ),
    path(
        "projects/deconfliction/create/<int:pk>",
        views.DeconflictionCreate.as_view(),
        name="project_deconfliction_create",
    ),
    path(
        "projects/deconfliction/update/<int:pk>",
        views.DeconflictionUpdate.as_view(),
        name="project_deconfliction_update",
    ),
]

ghostwriter/users/urls.py
"""This contains all of the URL mappings used by the Users application."""

# Django Imports
from django.urls import path

# Ghostwriter Libraries
from ghostwriter.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
    userprofile_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path(
        "<str:username>/", user_detail_view, name="user_detail"
    ),
    path(
        "<str:username>/update/", user_update_view, name="user_update"
    ),
    path("<str:username>/update/avatar/", view=userprofile_update_view, name="userprofile_update"),
]

ghostwriter/reporting/templates/reporting/evidence_form.html
{% extends "base_generic.html" %}

{% block pagetitle %}Evidence Form{% endblock %}

{% block content %}
    {% include "reporting/evidence_form_template.html" with form=form %}
{% endblock %}

ghostwriter/reporting/templates/reporting/finding_detail.html
{% extends "base_generic.html" %}

{% load bleach_tags %}

{% block pagetitle %}{{ finding.title }} Details{% endblock %}

{% block breadcrumbs %}
    <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
            <li class="breadcrumb-item"><a href="{% url 'home:dashboard' %}">Dashboard</a></li>
            <li class="breadcrumb-item"><a href="{% url 'reporting:findings' %}">Findings</a></li>
            <li class="breadcrumb-item active" aria-current="page">{{ finding.title }}</li>
        </ul>
    </nav>
{% endblock %}

{% block content %}

    <div class="dropdown">
        <div class="dropdown-menu-btn" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" onclick="hamburger(this)">
            <div class="bar1"></div>
            <div class="bar2"></div>
            <div class="bar3"></div>
        </div>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="finding-dropdown-btn">
            <a class="dropdown-item icon edit-icon" href="{% url 'reporting:finding_update' finding.id %}">Edit</a>
            <a class="dropdown-item icon add-icon js-assign-finding" assign-finding-id="{{ finding.id }}" href="javascript:void(0);" assign-finding-csrftoken="{{ csrf_token }}" assign-finding-url="{% url 'reporting:ajax_assign_finding' finding.id %}">Add to Report</a>
            <a class="dropdown-item icon back-arrow-icon" href="{% url 'reporting:findings' %}">Return to Findings</a>
            <a class="dropdown-item icon trash-icon" href="{% url 'reporting:finding_delete' finding.id %}">Delete</a>
        </div>
    </div>

    <div class="container">
        <h2>{{ finding.title }}</h2>
    </div>

    <!-- Finding Severity Badge -->
    <div>
        <span class="px-3 py-2 badge badge-dark severity-badge
            {% if finding.severity.severity == "Critical" %}
                critical-background
            {% elif finding.severity.severity == "High" %}
                high-background
            {% elif finding.severity.severity == "Medium" %}
                medium-background
            {% elif finding.severity.severity == "Low" %}
                low-background
            {% endif %}
            icon
            {% if finding.finding_type.finding_type == "Cloud" %}
                cloud-icon
            {% elif finding.finding_type.finding_type == "Host" %}
                host-icon
            {% elif finding.finding_type.finding_type == "Mobile" %}
                mobile-icon
            {% elif finding.finding_type.finding_type == "Network" %}
                network-icon
            {% elif finding.finding_type.finding_type == "Physical" %}
                physical-icon
            {% elif finding.finding_type.finding_type == "Web" %}
                code-icon
            {% elif finding.finding_type.finding_type == "Wireless" %}
                wireless-icon
            {% else %}
                bug-icon
            {% endif %}"
            {% if finding.cvss_score %}
                style="cursor: help"
                data-toggle="tooltip"
                data-placement="bottom"
                title="{{ finding.cvss_vector }}"
            {% endif %}
        >
            {{ finding.severity.severity }} {{ finding.cvss_score }}
        </span>
    </div>

    <div id="description" title="description">
        <h3 class="finding-header icon writing-icon">Description</h3>
        <hr class="finding-hr" />
        <div class="finding-content">
            {% if finding.description %}
                {{ finding.description|bleach }}
            {% else %}
                <p>Description write-up is needed.</p>
            {% endif %}
        </div>
    </div>

    <div id="impact" title="impact">
        <h3 class="finding-header icon impact-icon">Impact</h3>
        <hr class="finding-hr" />
        <div class="finding-content">
            {% if finding.impact %}
                {{ finding.impact|bleach }}
            {% else %}
                <p>Impact write-up is needed.</p>
            {% endif %}
        </div>
    </div>

    <div id="impact" title="impact">
        <h3 class="finding-header icon help-icon">Recommendations</h3>
        <hr class="finding-hr" />
        <div class="finding-content">
            {% if finding.mitigation %}
                {{ finding.mitigation|bleach }}
            {% else %}
                <p>Recommendations are needed.</p>
            {% endif %}
        </div>
    </div>

    <div id="detection" title="detection">
        <h3 class="finding-header icon shield-icon">Detection Recommendations</h3>
        <hr class="finding-hr" />
        <div class="finding-content">
            {% if finding.host_detection_techniques %}
                <h4 class="text-center">Host Detection</h4>
                <hr>
                {{ finding.host_detection_techniques|bleach }}
            {% endif %}

            {% if finding.network_detection_techniques %}
                <h4 class="text-center">Network Detection</h4>
                <hr>
                {{ finding.network_detection_techniques|bleach }}
            {% endif %}

            {% if not finding.network_detection_techniques and not finding.host_detection_techniques %}
                <p>No host or network detections have been written for this finding.</p>
            {% endif %}
        </div>
    </div>

    <div id="replication" title="replication">
        <h3 class="finding-header icon ol-list-icon">Replication Steps</h3>
        <hr class="finding-hr" />
        <div class="finding-content">
            {% if finding.replication_steps %}
                {{ finding.replication_steps|bleach }}
            {% else %}
                <p>Replication steps are needed.</p>
            {% endif %}
        </div>
    </div>

    <div id="references" title="references">
        <h3 class="finding-header icon link-icon">References</h3>
        <hr class="finding-hr" />
        <div class="finding-content">
            {% if finding.references %}
                {{ finding.references|bleach }}
            {% else %}
                <p>References are needed.</p>
            {% endif %}
        </div>
    </div>

    {% if finding.finding_guidance %}
        <div id="guidance" title="guidance">
            <h3 class="finding-header icon help-icon">Finding Guidance</h3>
            <hr class="finding-hr" />
            <div class="finding-content">
                {{ finding.finding_guidance|bleach }}
            </div>
        </div>
    {% endif %}

    <h3 class="finding-header icon comment-icon">Notes</h3>
    <hr class="finding-hr" />

    <p class="text-center">
        <a class="icon add-icon btn btn-primary mb-1" href="{% url 'reporting:finding_note_add' finding.id %}">Add a Note</a>
    </p>

    {% if finding.findingnote_set.all %}
        {% for note in finding.findingnote_set.all reversed %}
            <div id="note-container-{{ note.id }}">
                <div class="container note-container {% if forloop.counter|divisibleby:2 %}darker{% endif %}">
                    <div class="float-left col-10 col-md-10 col-sm-8">
                        {{ note.note|bleach }}
                    </div>

                    <div class="float-right col-2 col-md-2 col-sm-4">
                        <div>{% if note.operator %}<a class="note-link" href="{% url 'users:user_detail' note.operator.username %}">{{ note.operator.username }}</a>{% else %}<span class="note-link">Deleted</span>{% endif %}</div>
                        <div><p class="note-time">{{ note.timestamp }}</p></div>
                    </div>
                </div>
            </div>

            {% if request.user == note.operator or request.user.is_staff %}
                <div class="pb-3">
                    <a class="note-link" href="{% url 'reporting:finding_note_edit' note.id %}">Edit</a> |
                    <a id="note-delete-button-{{ note.id }}" class="js-confirm-delete note-link" data-toggle="modal" data-target="#confirm-delete-modal" href="javascript:void(0);" delete-target-csrftoken="{{ csrf_token }}" delete-target-url="{% url 'reporting:ajax_delete_finding_note' note.id%}" delete-target-id="{{ note.id }}" delete-target-type="note">Delete</a>
                </div>
            {% endif %}
        {% endfor %}
    {% else %}
        <p>No notes for this finding.</p>
    {% endif %}
{% endblock %}

{% block morescripts %}
    {% comment %} Include the reusable delete confirmation modal and related scripts {% endcomment %}
    {% include "confirm_delete_modal.html" %}

    <!-- Assign Finding with AJAX -->
    <script>
        $('.js-assign-finding').click(function () {
            var url = $(this).attr('assign-finding-url');
            var findingId = $(this).attr('assign-finding-id');
            var csrftoken = $(this).attr('assign-finding-csrftoken')
            // Prep AJAX request with CSRF token
            $.ajaxSetup({
                beforeSend: function(xhr, settings) {
                    if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                        xhr.setRequestHeader('X-CSRFToken', csrftoken);
                    }
                }
            });
            // Send AJAX POST request
            $.ajax({
                url: url,
                type: 'POST',
                dataType: 'json',
                data: {
                    'finding': findingId
                },
                success: function (data) {
                    if (data['result'] == 'success') {
                        // Something
                    }
                    if (data['message']) {
                        displayToastTop({type:data['result'], string:data['message'], title:'Finding Assigned'});
                    }
                }
            });
        });
    </script>
{% endblock %}

ghostwriter/reporting/templates/reporting/report_form.html
{% extends "base_generic.html" %}
{% load crispy_forms_tags %}

{% block pagetitle %}Report Creation{% endblock %}

{% block breadcrumbs %}
    <nav aria-label="breadcrumb">
        <ul class="breadcrumb">
        {% comment %} Create breadcrumbs based on the context of the request {% endcomment %}
            <li class="breadcrumb-item"><a href="{% url 'home:dashboard' %}">Dashboard</a></li>
            {% comment %} Check if `project` is in context to determine if this is for a specific project {% endcomment %}
            {% if project %}
                <li class="breadcrumb-item"><a href="{% url 'rolodex:client_detail' project.client.id %}">{{ project.client.name }}</a></li>
                <li class="breadcrumb-item"><a href="{% url 'rolodex:project_detail' project.id %}">{{ project }}</a></li>
                <li class="breadcrumb-item active" aria-current="page">Project Report</li>
            {% else %}
                <li class="breadcrumb-item"><a href="{% url 'reporting:reports' %}">Reports</a></li>
                <li class="breadcrumb-item active" aria-current="page">New Report Form</li>
            {% endif %}
        </ul>
    </nav>
{% endblock %}

{% block content %}
    <!-- Instructions Section -->
    <p>Provide a meaningful name for this report, select the project to which it should be associated, and optionally select report templates to use:</p>

    <!-- Form Error Section -->
    {% if form.errors %}
        <script>
            {% for field in form %}
                {% for error in field.errors %}
                    displayToastTop({type:'error', string:'{{ error }}', context:'form'});
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                displayToastTop({type:'error', string:'{{ error }}', context:'form'});
            {% endfor %}
        </script>
    {% endif %}

    <!-- Form Section -->
    {% crispy form form.helper %}
{% endblock %}